#!/usr/bin/env python3
"""Generated by forge-sdlc-harness (harness build) — do not edit; edits are drift.

Locates the real runner and hands off. The machinery is shared (D-030 B1/B5):
one copy per harness COMMIT, not one copy per repo. This file exists only so
that every entry point that already knows the path `.harness/runner.py` — a
repo-rooted session's hooks, a habit, a script — keeps working.

Resolution order:
  1. the pinned commit in the local harness cache, which is what the consumer
     was actually built from;
  2. a sibling `forge-sdlc-harness` checkout, for when the cache has been
     cleared or the repo was cloned fresh.

Failing to resolve exits 2 and says so. Enforcement that cannot execute must
never look like enforcement that passed.
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
CONSUMER = os.path.dirname(HERE)


def pinned_sha():
    try:
        with open(os.path.join(HERE, "lock.json")) as f:
            return (json.load(f).get("source") or {}).get("sha") or ""
    except (OSError, ValueError):
        return ""


def candidates():
    sha = pinned_sha()
    out = []
    if sha:
        out.append(
            os.path.join(
                os.path.expanduser("~/.cache/forge-harness"),
                sha,
                "core",
                "runner",
                "runner.py",
            )
        )
    # Sibling checkout: the flat layout guarantees where this is, and it is
    # the only fallback that works when the cache has been cleared.
    out.append(
        os.path.join(
            os.path.dirname(CONSUMER), "forge-sdlc-harness", "core", "runner", "runner.py"
        )
    )
    return out


def main():
    tried = candidates()
    for c in tried:
        if os.path.isfile(c):
            # setdefault, not assignment: the root dispatcher sets this to
            # name which consumer it is driving, and that must win.
            os.environ.setdefault("HARNESS_CONSUMER_ROOT", CONSUMER)
            os.execv(sys.executable, [sys.executable, c] + sys.argv[1:])
    sys.stderr.write(
        "harness: cannot locate the runner for %s.\n"
        "harness: looked in:\n%s\n"
        "harness: nothing is being enforced here. Re-run `harness build` for this\n"
        "harness: consumer, or restore the forge-sdlc-harness checkout.\n"
        % (CONSUMER, "\n".join("  - " + t for t in tried))
    )
    sys.exit(2)


if __name__ == "__main__":
    main()
