//! Embed the runtime-owned platform-schema bundle, by reference.
//!
//! `forge schema compile` (TS-0) needs the runtime-owned table schemas —
//! the canonical JSON under
//! `forge-runtime/crates/forge-runtime-auth/schemas/`, the single source of
//! truth `bootstrap_owned_schemas` applies at workspace boot. Copying those
//! files into consumer trees is the disease the compiled snapshot cures
//! (the portal's `platform-schemas/` copies drifted to `archetype: Base`
//! within weeks), so the CLI embeds them at BUILD time from the canonical
//! path instead — the same by-relative-path pattern `forge-sdk-v2` uses for
//! the WIT contract. The file list is enumerated here, never hand-written:
//! a table added to the bundle is in the next CLI build with no edit in
//! this repo.
//!
//! The flat sibling layout is load-bearing (working-root contract); CI
//! reproduces it with a sibling checkout of `forge-runtime`.

use std::fmt::Write as _;
use std::path::PathBuf;

/// Where the canonical bundle lives, relative to this crate — and the
/// `source` string the emitted snapshot records as its pin.
const BUNDLE_DIR: &str = "../forge-runtime/crates/forge-runtime-auth/schemas";

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let bundle_dir = manifest_dir.join(BUNDLE_DIR);
    println!("cargo:rerun-if-changed={}", bundle_dir.display());

    let mut files: Vec<PathBuf> = std::fs::read_dir(&bundle_dir)
        .unwrap_or_else(|e| {
            panic!(
                "cannot read the runtime-owned schema bundle at {} \
                 (the flat sibling layout is required — is forge-runtime \
                 checked out beside forge-cli?): {e}",
                bundle_dir.display()
            )
        })
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().map(|e| e == "json").unwrap_or(false))
        .collect();
    files.sort();

    let mut out = String::new();
    writeln!(
        out,
        "// @generated by build.rs from {BUNDLE_DIR} — do not edit\n"
    )
    .unwrap();
    writeln!(
        out,
        "/// The snapshot's `platform_bundle.source` pin: where these bytes are canonical."
    )
    .unwrap();
    writeln!(
        out,
        "pub const PLATFORM_BUNDLE_SOURCE: &str = \
         \"forge-runtime/crates/forge-runtime-auth/schemas\";"
    )
    .unwrap();
    writeln!(
        out,
        "/// Every runtime-owned table schema, `(file name, canonical JSON)`, sorted by file."
    )
    .unwrap();
    writeln!(out, "pub const PLATFORM_BUNDLE: &[(&str, &str)] = &[").unwrap();
    for file in &files {
        println!("cargo:rerun-if-changed={}", file.display());
        let name = file.file_name().unwrap().to_string_lossy();
        writeln!(
            out,
            "    ({name:?}, include_str!({:?})),",
            file.canonicalize().unwrap().display().to_string()
        )
        .unwrap();
    }
    writeln!(out, "];").unwrap();

    let out_path = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("platform_bundle.gen.rs");
    std::fs::write(out_path, out).unwrap();
}
