//! Subcommand modules. One file per top-level `forge <verb>`.

pub mod branch;
pub mod brand;
pub mod build;
pub mod check;
pub mod components;
pub(crate) mod contract_diff;
pub mod deploy;
pub mod dev;
pub mod domain;
pub mod email;
mod from_trace;
pub mod init;
pub mod login;
pub mod logout;
pub mod logs;
pub mod new;
pub mod pages;
pub mod pull;
pub mod push;
mod push_diff;
pub mod schema;
pub mod sdk;
pub mod secrets;
pub mod ship;
pub mod sso;
pub mod static_cmd;
pub mod surface_lint;
pub mod tenant;
pub mod test;
pub mod tokens;
pub mod units;
pub mod update;
pub mod wasm_upload;
pub mod whoami;
pub mod ws;
