//! Keeping a lane worktree's path out of the files this binary generates.
//!
//! Two of the files `forge` writes are GENERATED AND COMMITTED: a portal
//! domain's `Cargo.toml`, regenerated by `forge wasm-build`, and a scaffold's,
//! written by `forge new`. Both carry path dependencies on `forge-lang-rt` and
//! `forge-sdk-v2`, and both get those paths from `env!("CARGO_MANIFEST_DIR")`
//! — the directory the emitter was COMPILED in, which is true on the box that
//! built it and nowhere else.
//!
//! In the flat working root that directory is usually the canonical checkout
//! and the emitted path is right. It is wrong the moment the binary was built
//! in a worktree lane. FU-11, 2026-09-10: a peer borrowed
//! `forge-cli--hs10-css-report/target/release/forge` because it was the only
//! binary new enough, and running it rewrote `domains/billing/Cargo.toml` to
//! path-dep on `../../../forge-lang--host-surface/crates/forge-lang-rt`. Every
//! cargo command after that died on a lockfile package collision, and the
//! contamination was a committed path that looked deliberate.
//!
//! The hazard is not the borrowing. Nothing stops a lane binary being used and
//! nothing should — `build-bins-worktree.sh` stages binaries built in
//! `--devbuild` lanes on purpose — and a rule saying "don't borrow one" would
//! be a hand-obligation with no mechanism under it. So the generator answers
//! instead. A path that points into `<repo>--<branch>` is rewritten to the
//! `<repo>` beside it before it reaches a file, and the rewrite says so on
//! stderr, because swapping a dependency under someone silently is its own way
//! to waste an afternoon. When there is no `<repo>` beside it the rewrite has
//! no answer, and that is a refusal naming the binary to use instead — writing
//! the lane path would be the FU-11 outcome and inventing a path that is not
//! there would be a stranger error one step later.
//!
//! `FORGE_LANG_ALLOW_LANE_PATHS=1` opts back in, for the one case that wants
//! it: developing `forge-lang-rt` itself in a lane, where the emitted code
//! needs the lane's rt and a local build is the whole point. It is an env var
//! rather than a flag because the callers are `forge wasm-build`, `forge ship`
//! and `forge dev`, and a flag would have to be threaded through all three to
//! be usable from any of them.

use std::path::{Component, Path, PathBuf};

use anyhow::{Result, bail};

/// Set to `1` to write lane paths into generated files anyway.
pub const ALLOW_VAR: &str = "FORGE_LANG_ALLOW_LANE_PATHS";

/// The first worktree-lane component in `path`, if any.
///
/// A lane in the working root is `<repo>--<branch>`, a flat sibling of
/// `<repo>` (root `CLAUDE.md`: the flat layout is load-bearing), so the test
/// is per-component and purely lexical. Both halves must be non-empty: a
/// directory literally named `--x` or `x--` is not a lane and is far more
/// likely to be someone's real directory.
fn lane_component(path: &Path) -> Option<String> {
    path.components().find_map(|c| match c {
        Component::Normal(name) => name
            .to_str()
            .and_then(|n| n.split_once("--"))
            .filter(|(repo, branch)| !repo.is_empty() && !branch.is_empty())
            .map(|_| name.to_string_lossy().into_owned()),
        _ => None,
    })
}

/// `path` with every worktree-lane component replaced by the canonical repo
/// beside it.
///
/// Returns `path` unchanged when there is no lane component, or when the
/// de-laned path is not an existing directory. That last case is the whole
/// safety argument: a wrong path that exists is a confusing build and a wrong
/// path that does not exist is a confusing error, so the rewrite only fires
/// when it can land somewhere real. A `--` in a directory name that is not a
/// lane therefore costs nothing.
pub fn de_lane(path: &Path) -> PathBuf {
    let mut out = PathBuf::new();
    let mut rewrote = false;
    for component in path.components() {
        match component {
            Component::Normal(name) => match name
                .to_str()
                .and_then(|n| n.split_once("--"))
                .filter(|(repo, branch)| !repo.is_empty() && !branch.is_empty())
            {
                Some((repo, _)) => {
                    out.push(repo);
                    rewrote = true;
                }
                None => out.push(name),
            },
            other => out.push(other.as_os_str()),
        }
    }
    if rewrote && out.is_dir() {
        out
    } else {
        path.to_path_buf()
    }
}

/// The path to write into a generated, committed manifest for `what`.
///
/// The canonical sibling when `path` is lane-wired and one exists; `path`
/// itself when it is not lane-wired at all; an error when it is lane-wired
/// and there is nothing canonical to fall back to.
pub fn resolve(what: &str, path: &Path) -> Result<PathBuf> {
    let Some(lane) = lane_component(path) else {
        return Ok(path.to_path_buf());
    };
    if std::env::var(ALLOW_VAR).ok().as_deref() == Some("1") {
        eprintln!(
            "warning: {ALLOW_VAR}=1 — writing the lane path for `{what}` into a generated file:\n  \
             {}\n  \
             That file is committed, so this path travels to every checkout that reads it. \
             Do not commit the result (FU-11).",
            path.display(),
        );
        return Ok(path.to_path_buf());
    }
    let canonical = de_lane(path);
    if canonical != path {
        eprintln!(
            "note: this `forge` was built in the worktree lane `{lane}`, so its `{what}` path \
             points there:\n  \
             {}\n\
             Generated manifests are COMMITTED and a lane path in one breaks every checkout that \
             reads it (FU-11), so the canonical sibling is emitted instead:\n  \
             {}\n\
             Set {} to choose a different tree, or {ALLOW_VAR}=1 to keep the lane path.",
            path.display(),
            canonical.display(),
            override_var(what),
        );
        return Ok(canonical);
    }
    bail!(
        "refusing to generate a manifest: this `forge` was built in the worktree lane `{lane}`, \
         so its `{what}` path points into that lane —\n  {}\n\
         and there is no canonical `{}` beside it to emit instead. Generated manifests are \
         COMMITTED, and a lane path in one breaks every checkout that reads it (FU-11).\n\
         Use the staged binary at `forge-cli/target/release/forge` \
         (`forge-platform-operations/dev/build-bins-worktree.sh` builds and stages it), or set \
         {} to a checkout that exists, or {ALLOW_VAR}=1 to write the lane path anyway.",
        path.display(),
        lane.split_once("--").map(|(repo, _)| repo).unwrap_or(&lane),
        override_var(what),
    )
}

/// The env var that overrides `what`, named in every message about it.
fn override_var(what: &str) -> &'static str {
    match what {
        "forge-sdk-v2" => "FORGE_SDK_PATH",
        _ => "FORGE_LANG_RT_PATH",
    }
}

/// Where this binary thinks `forge-lang-rt` is, before any de-laning: an
/// explicit `FORGE_LANG_RT_PATH`, else the emitter's compile-time sibling.
pub fn rt_source() -> PathBuf {
    match std::env::var("FORGE_LANG_RT_PATH") {
        Ok(explicit) => PathBuf::from(explicit),
        Err(_) => forge_lang_rustgen::default_rt_path(),
    }
}

/// The `forge-sdk-v2` twin of [`rt_source`]. `FORGE_SDK_PATH` is the variable
/// `forge new` already documents, rather than a second one meaning the same
/// thing.
pub fn sdk_source() -> PathBuf {
    match std::env::var("FORGE_SDK_PATH") {
        Ok(explicit) => PathBuf::from(explicit),
        Err(_) => forge_lang_rustgen::default_sdk_path(),
    }
}

#[cfg(test)]
pub(crate) mod tests {
    use super::*;

    /// `ALLOW_VAR` is process-global and `cargo test` is threaded, so a test
    /// that SETS it and a test that depends on it being unset are a race, not
    /// a pair of independent tests. Every test in the crate that reads or
    /// writes it takes this first. Held across the whole body rather than
    /// just the `set_var`, because the read happens inside the code under
    /// test.
    pub(crate) static ENV_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

    /// A scratch working root, in the layout every lane on the real disk has:
    /// `<repo>` and `<repo>--<branch>` as flat siblings.
    pub(crate) fn working_root() -> tempfile::TempDir {
        let dir = tempfile::tempdir().unwrap();
        for repo in ["forge-lang", "forge-lang--host-surface"] {
            std::fs::create_dir_all(dir.path().join(repo).join("crates/forge-lang-rt")).unwrap();
        }
        std::fs::create_dir_all(dir.path().join("forge-sdk-v2")).unwrap();
        std::fs::create_dir_all(dir.path().join("forge-sdk-v2--lane")).unwrap();
        dir
    }

    #[test]
    fn the_incidents_path_becomes_the_canonical_sibling() {
        let _guard = ENV_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let root = working_root();
        let lane = root
            .path()
            .join("forge-lang--host-surface/crates/forge-lang-rt");
        assert_eq!(
            de_lane(&lane),
            root.path().join("forge-lang/crates/forge-lang-rt"),
        );
        assert_eq!(
            resolve("forge-lang-rt", &lane).unwrap(),
            root.path().join("forge-lang/crates/forge-lang-rt"),
        );
    }

    #[test]
    fn a_repo_root_lane_is_de_laned_too() {
        let root = working_root();
        assert_eq!(
            de_lane(&root.path().join("forge-sdk-v2--lane")),
            root.path().join("forge-sdk-v2"),
        );
    }

    #[test]
    fn a_canonical_path_is_returned_unchanged() {
        let _guard = ENV_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let root = working_root();
        let canonical = root.path().join("forge-lang/crates/forge-lang-rt");
        assert_eq!(de_lane(&canonical), canonical);
        assert_eq!(resolve("forge-lang-rt", &canonical).unwrap(), canonical);
    }

    /// The de-laned path has to exist, so a lane whose canonical sibling was
    /// never cloned has no rewrite available — and that is the refusal, not a
    /// shrug. The message has to name the binary to use instead, because
    /// "your binary is in the wrong place" is only actionable with one.
    #[test]
    fn a_lane_with_no_canonical_sibling_is_a_refusal_naming_the_staged_binary() {
        let _guard = ENV_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let root = working_root();
        let orphan = root.path().join("forge-nowhere--lane/crates/forge-lang-rt");
        std::fs::create_dir_all(&orphan).unwrap();
        assert_eq!(de_lane(&orphan), orphan);

        let err = format!("{:#}", resolve("forge-lang-rt", &orphan).unwrap_err());
        assert!(err.contains("forge-nowhere--lane"), "{err}");
        assert!(err.contains("forge-cli/target/release/forge"), "{err}");
        assert!(err.contains("build-bins-worktree.sh"), "{err}");
        assert!(err.contains("FORGE_LANG_RT_PATH"), "{err}");
    }

    /// `--` is a lane convention, not a reserved sequence. A real directory
    /// that happens to contain it, with no sibling to fall back to, keeps its
    /// name — but it is still a refusal rather than a silent write, because
    /// the two are indistinguishable from here and the safe answer is the one
    /// that asks.
    #[test]
    fn a_leading_or_trailing_double_dash_is_not_a_lane() {
        let _guard = ENV_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let root = working_root();
        for odd in ["--leading", "trailing--"] {
            let path = root.path().join(odd);
            std::fs::create_dir_all(&path).unwrap();
            assert_eq!(lane_component(&path), None, "{odd}");
            assert_eq!(resolve("forge-lang-rt", &path).unwrap(), path, "{odd}");
        }
    }

    #[test]
    fn the_opt_in_keeps_the_lane_path() {
        let _guard = ENV_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let root = working_root();
        let lane = root
            .path()
            .join("forge-lang--host-surface/crates/forge-lang-rt");
        unsafe { std::env::set_var(ALLOW_VAR, "1") };
        let resolved = resolve("forge-lang-rt", &lane);
        unsafe { std::env::remove_var(ALLOW_VAR) };
        assert_eq!(resolved.unwrap(), lane);
    }
}
